const Product = require('../models/Product');
const fs = require('fs');
const { generateProductSlug, ensureUniqueSlug, validateSlug } = require('../utils/slugGenerator');
const { autoGenerateProductSEO, validateSEOFields } = require('../utils/seoUtils');
const { generateImageVariants } = require('../utils/imageProcessor');
const apiCache = require('../middleware/apiCacheMiddleware');

// Add a new product
const addProduct = async (req, res) => {
  try {
    console.log('=== ADD PRODUCT REQUEST ===');
    console.log('Request body:', req.body);
    console.log('File:', req.file ? req.file.originalname : 'No file');
    
    const { 
      title, 
      keywords, 
      description, 
      price, 
      categories,
      // SEO Fields
      seoTitle,
      seoDescription,
      imageAlt,
      metaKeywords,
      focusKeyword,
      shortDescription,
      // Featured spotlight controls (optional)
      featuredUntil,
      isSoldOut
    } = req.body;

    console.log('Extracted fields:', { title, keywords, description, price, categories });

    if (!title || !keywords || !description || !price || !categories || !req.file) {
      console.log('Validation failed - missing required fields');
      return res.status(400).json({ message: 'All required fields must be provided (title, keywords, description, price, categories, image)' });
    }

    // Parse arrays from JSON strings
    const parsedKeywords = typeof keywords === 'string' ? keywords.split(',').map(keyword => keyword.trim()) : keywords;
    const parsedCategories = typeof categories === 'string' ? JSON.parse(categories) : categories;
    const parsedMetaKeywords = metaKeywords ? (typeof metaKeywords === 'string' ? metaKeywords.split(',').map(k => k.trim()) : metaKeywords) : [];

    // Prepare basic product data
    const productData = {
      title: title.trim(),
      keywords: parsedKeywords,
      description: description.trim(),
      price: parseFloat(price),
      categories: parsedCategories,
      image: req.file.path,
      // SEO fields (if provided)
      seoTitle: seoTitle?.trim(),
      seoDescription: seoDescription?.trim(),
      imageAlt: imageAlt?.trim(),
      metaKeywords: parsedMetaKeywords,
      focusKeyword: focusKeyword?.trim().toLowerCase(),
      shortDescription: shortDescription?.trim(),
      // Featured spotlight controls
      featuredUntil: featuredUntil ? new Date(featuredUntil) : null,
      isSoldOut: String(isSoldOut).toLowerCase() === 'true'
    };

    // Auto-generate missing SEO fields
    const autoGeneratedSEO = autoGenerateProductSEO(productData);
    const completeProductData = { ...productData, ...autoGeneratedSEO };

    // Generate and ensure unique slug
    const baseSlug = generateProductSlug(title, parsedCategories);
    completeProductData.slug = await ensureUniqueSlug(baseSlug, Product);

    // Validate SEO fields
    const seoValidation = validateSEOFields(completeProductData);
    if (!seoValidation.isValid) {
      console.log('SEO Validation failed:', seoValidation.errors);
      return res.status(400).json({ 
        message: 'SEO validation failed', 
        errors: seoValidation.errors,
        details: {
          seoTitle: `"${completeProductData.seoTitle}" (${completeProductData.seoTitle?.length || 0} chars)`,
          seoDescription: `"${completeProductData.seoDescription}" (${completeProductData.seoDescription?.length || 0} chars)`,
          imageAlt: `"${completeProductData.imageAlt}" (${completeProductData.imageAlt?.length || 0} chars)`
        }
      });
    }

    // Create and save the product
    const newProduct = new Product(completeProductData);
    const savedProduct = await newProduct.save();
    
    // Fire-and-forget: generate AVIF/WebP variants in background
    if (req.file?.path) {
      generateImageVariants(req.file.path).catch(err => 
        console.error('Background image processing failed:', err.message)
      );
    }
    
    console.log('Product saved successfully:', savedProduct.title);
    
    // Clear API cache so product listings update immediately
    apiCache.clear();
    
    const responseData = {
      success: true,
      message: 'Product created successfully',
      product: savedProduct,
      seoScore: savedProduct.seoScore
    };
    
    console.log('Sending response:', responseData);
    res.status(201).json(responseData);
  } catch (error) {
    console.error('=== ADD PRODUCT ERROR ===');
    console.error('Error adding product:', error);
    console.error('Error stack:', error.stack);
    
    const errorResponse = { 
      success: false, 
      message: error.message 
    };
    
    console.log('Sending error response:', errorResponse);
    res.status(500).json(errorResponse);
  }
};
const getProductsByCategory = async (req, res) => {
  try {
    const categoryName = req.params.categoryName.replace(/-/g, " ");
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 20;
    const skip = (page - 1) * limit;

    // Create case-insensitive regex for category matching
    const categoryRegex = new RegExp(`^${categoryName}$`, "i");
    const query = {
      categories: categoryRegex,
      isActive: true
    };

    // Run queries in parallel for better performance
    const [products, total] = await Promise.all([
      Product.find(query)
        .select('title slug image images categories price seoTitle seoDescription imageAlt shortDescription createdAt featuredUntil isSoldOut soldOutAt')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      
      Product.countDocuments(query)
    ]);

    const hasMore = products.length === limit;
    const totalPages = Math.ceil(total / limit);

    // Set cache headers
    res.set({
      'Cache-Control': 'public, max-age=300',
      'X-Total-Count': total,
      'X-Page': page,
      'X-Has-More': hasMore
    });

    res.json({
      products,
      total,
      page,
      limit,
      totalPages,
      hasMore
    });
  } catch (error) {
    console.error('getProductsByCategory error:', error);
    res.status(500).json({ message: error.message });
  }
};
// Get all products (optimized for large datasets)
const getAllProducts = async (req, res) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 20;
    const skip = (page - 1) * limit;
    const searchTerm = req.query.search ? req.query.search.trim() : '';
    const categoryFilter = req.query.category ? req.query.category.trim() : '';

    // Admin routes should see ALL products; public routes only active ones.
    const isAdminRoute = req.baseUrl && req.baseUrl.includes('/admin');
    const query = isAdminRoute ? {} : { isActive: { $ne: false } };

    // Apply search filter — searches all name/label fields including seoTitle (shown on product page)
    if (searchTerm) {
      const regex = new RegExp(searchTerm, 'i');
      query.$or = [
        { title: regex },
        { seoTitle: regex },
        { slug: regex },
        { keywords: regex },
        { categories: regex },
        { description: regex }
      ];
    }

    // Apply category filter
    if (categoryFilter) {
      query.categories = categoryFilter;
    }

    const [products, total] = await Promise.all([
      Product.find(query)
        .select('title slug image images categories price keywords description seoTitle seoDescription imageAlt shortDescription isActive createdAt featuredUntil isSoldOut soldOutAt')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      Product.countDocuments(query)
    ]);

    // Calculate if there are more pages (for infinite scroll)
    const hasMore = products.length === limit;
    const totalPages = Math.ceil(total / limit);

    // Set aggressive cache headers for API response
    res.set({
      'Cache-Control': 'public, max-age=300', // Cache for 5 minutes
      'X-Total-Count': total, // Useful for clients
      'X-Page': page,
      'X-Has-More': hasMore
    });
    
    res.json({
      products,
      total,
      page,
      limit,
      totalPages,
      hasMore
    });
  } catch (error) {
    console.error('getAllProducts error:', error);
    res.status(500).json({ message: error.message });
  }
};

// Get product by ID or slug
const getProductById = async (req, res) => {
  try {
    const { id } = req.params;
    let product;

    // Try to find by slug first, then by ID
    if (id.match(/^[0-9a-fA-F]{24}$/)) {
      // It's a valid ObjectId
      product = await Product.findById(id);
    } else {
      // It's likely a slug
      product = await Product.findOne({ slug: id.toLowerCase() });
    }

    if (!product) {
      return res.status(404).json({ message: 'Product not found' });
    }

    // Increment view count
    await Product.findByIdAndUpdate(product._id, { $inc: { viewCount: 1 } });

    res.json(product);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get product by slug (dedicated endpoint)
const getProductBySlug = async (req, res) => {
  try {
    const { slug } = req.params;
    
    const product = await Product.findOne({ 
      slug: slug.toLowerCase(),
      isActive: true 
    });

    if (!product) {
      return res.status(404).json({ message: 'Product not found' });
    }

    // Increment view count
    await Product.findByIdAndUpdate(product._id, { $inc: { viewCount: 1 } });

    res.json(product);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
const updateProduct = async (req, res) => {
  try {
    const { 
      title, 
      keywords, 
      description, 
      price, 
      categories,
      // SEO Fields
      seoTitle,
      seoDescription,
      imageAlt,
      metaKeywords,
      focusKeyword,
      shortDescription,
      // Featured spotlight controls
      featuredUntil,
      isSoldOut
    } = req.body;

    const product = await Product.findById(req.params.id);
    if (!product) {
      return res.status(404).json({ message: 'Product not found' });
    }

    // Parse arrays from JSON strings
    const parsedKeywords = typeof keywords === 'string' ? keywords.split(',').map(keyword => keyword.trim()) : keywords;
    const parsedCategories = typeof categories === 'string' ? JSON.parse(categories) : categories;
    const parsedMetaKeywords = metaKeywords ? (typeof metaKeywords === 'string' ? metaKeywords.split(',').map(k => k.trim()) : metaKeywords) : product.metaKeywords;

    // Prepare updated fields
    const updatedFields = {
      title: title?.trim() || product.title,
      keywords: parsedKeywords || product.keywords,
      description: description?.trim() || product.description,
      price: price ? parseFloat(price) : product.price,
      categories: parsedCategories || product.categories,
      // SEO fields
      // If title changed and seoTitle wasn't explicitly sent, clear it so autoGenerateProductSEO rebuilds from new title
      seoTitle: seoTitle?.trim() || (title?.trim() && title.trim() !== product.title ? '' : product.seoTitle),
      seoDescription: seoDescription?.trim() || product.seoDescription,
      imageAlt: imageAlt?.trim() || product.imageAlt,
      metaKeywords: parsedMetaKeywords,
      focusKeyword: focusKeyword?.trim().toLowerCase() || product.focusKeyword,
      shortDescription: shortDescription?.trim() || product.shortDescription,
      lastSEOUpdate: new Date()
    };

    // Featured spotlight controls (admin-managed)
    if (typeof featuredUntil !== 'undefined') {
      const raw = String(featuredUntil).trim();
      if (raw === '' || raw.toLowerCase() === 'null' || raw.toLowerCase() === 'undefined') {
        updatedFields.featuredUntil = null;
      } else {
        const d = new Date(raw);
        if (!Number.isNaN(d.getTime())) {
          updatedFields.featuredUntil = d;
        }
      }
    }

    if (typeof isSoldOut !== 'undefined') {
      const nextSold = String(isSoldOut).toLowerCase() === 'true';
      updatedFields.isSoldOut = nextSold;
      // Only stamp soldOutAt when transitioning to sold.
      if (nextSold && !product.isSoldOut) {
        updatedFields.soldOutAt = new Date();
      }
      if (!nextSold && product.isSoldOut) {
        updatedFields.soldOutAt = null;
      }
    }

    // Handle slug update if title or categories changed
    if (title && (title !== product.title || parsedCategories)) {
      const baseSlug = generateProductSlug(title, parsedCategories || product.categories);
      updatedFields.slug = await ensureUniqueSlug(baseSlug, Product, req.params.id);
    }

    // Auto-generate missing SEO fields
    const autoGeneratedSEO = autoGenerateProductSEO(updatedFields);
    Object.assign(updatedFields, autoGeneratedSEO);

    // Note: SEO validation is intentionally skipped on updates so admin edits
    // (title, description, categories etc.) are never blocked by SEO length rules.

    // Handle image update and old image deletion
    if (req.file) {
      // Delete old image
      if (product.image && fs.existsSync(product.image)) {
        fs.unlink(product.image, (err) => {
          if (err) {
            console.error('Failed to delete old image:', err);
          } else {
            console.log('Old image deleted:', product.image);
          }
        });
      }
      updatedFields.image = req.file.path;
      
      // Fire-and-forget: generate AVIF/WebP variants for new image
      generateImageVariants(req.file.path).catch(err => 
        console.error('Background image processing failed:', err.message)
      );
    }

    const updatedProduct = await Product.findByIdAndUpdate(req.params.id, updatedFields, { new: true });

    // Clear API cache so listings update immediately
    apiCache.clear();

    res.json({
      success: true,
      message: 'Product updated successfully',
      product: updatedProduct,
      seoScore: updatedProduct.seoScore
    });
  } catch (error) {
    console.error('Error updating product:', error);
    res.status(500).json({ message: error.message });
  }
};

const deleteProduct = async (req, res) => {
  try {
    const product = await Product.findByIdAndDelete(req.params.id);

    if (!product) {
      return res.status(404).json({ message: 'Product not found' });
    }

    // Delete image file from filesystem
    if (product.image && fs.existsSync(product.image)) {
      fs.unlink(product.image, (err) => {
        if (err) {
          console.error('Failed to delete image:', err);
        } else {
          console.log('Image deleted:', product.image);
        }
      });
    }

    res.json({ message: 'Product deleted successfully' });
    
    // Clear API cache
    apiCache.clear();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Server-side search for products (avoids fetching entire catalog client-side)
const searchProducts = async (req, res) => {
  try {
    const { q, page = 1, limit = 20 } = req.query;
    const skip = (parseInt(page) - 1) * parseInt(limit);

    if (!q || !q.trim()) {
      return res.json({ products: [], total: 0, page: 1, limit: parseInt(limit) });
    }

    const searchTerm = q.trim();

    // Use MongoDB text index for efficient search
    const textQuery = {
      $text: { $search: searchTerm },
      isActive: true
    };

    // Fallback: regex search if text search returns no results
    const regexQuery = {
      isActive: true,
      $or: [
        { title: { $regex: searchTerm, $options: 'i' } },
        { description: { $regex: searchTerm, $options: 'i' } },
        { keywords: { $regex: searchTerm, $options: 'i' } },
        { categories: { $regex: searchTerm, $options: 'i' } },
        { shortDescription: { $regex: searchTerm, $options: 'i' } }
      ]
    };

    // Try text search first (faster, uses index)
    let [products, total] = await Promise.all([
      Product.find(textQuery)
        .select('title slug image images categories price seoTitle seoDescription imageAlt shortDescription createdAt keywords featuredUntil isSoldOut soldOutAt')
        .sort({ score: { $meta: 'textScore' } })
        .skip(skip)
        .limit(parseInt(limit))
        .lean(),
      Product.countDocuments(textQuery)
    ]);

    // Fallback to regex if text search found nothing
    if (products.length === 0) {
      [products, total] = await Promise.all([
        Product.find(regexQuery)
          .select('title slug image images categories price seoTitle seoDescription imageAlt shortDescription createdAt keywords featuredUntil isSoldOut soldOutAt')
          .sort({ createdAt: -1 })
          .skip(skip)
          .limit(parseInt(limit))
          .lean(),
        Product.countDocuments(regexQuery)
      ]);
    }

    res.set({
      'Cache-Control': 'public, max-age=60',
      'X-Total-Count': total
    });

    res.json({
      products,
      total,
      page: parseInt(page),
      limit: parseInt(limit),
      totalPages: Math.ceil(total / parseInt(limit)),
      hasMore: products.length === parseInt(limit)
    });
  } catch (error) {
    console.error('searchProducts error:', error);
    res.status(500).json({ message: error.message });
  }
};

module.exports = {
  getProductsByCategory,
  addProduct,
  getAllProducts,
  getProductById,
  getProductBySlug,
  searchProducts,
  updateProduct,
  deleteProduct,
};
