#!/bin/bash

# Find line 58 and replace the ImageGallery component with one that has magnifier
awk '
/^\/\/ Image Gallery Component$/ {
    print "// Image Gallery Component with Magnifier"
    print "const ImageGallery = ({ images, productTitle }) => {"
    print "  const [currentImage, setCurrentImage] = useState(0);"
    print "  const [showMagnifier, setShowMagnifier] = useState(false);"
    print "  const [magnifierPosition, setMagnifierPosition] = useState({ x: 0, y: 0 });"
    print "  const [cursorPosition, setCursorPosition] = useState({ x: 0, y: 0 });"
    print ""
    print "  const imageArray = Array.isArray(images) ? images : [images].filter(Boolean);"
    print "  const processedImages = imageArray.map(img => getImagePath(img));"
    print ""
    print "  const nextImage = () => {"
    print "    setCurrentImage((prev) => (prev + 1) % processedImages.length);"
    print "  };"
    print ""
    print "  const prevImage = () => {"
    print "    setCurrentImage((prev) => (prev - 1 + processedImages.length) % processedImages.length);"
    print "  };"
    print ""
    print "  const handleMouseMove = (e) => {"
    print "    const { left, top, width, height } = e.currentTarget.getBoundingClientRect();"
    print "    const x = ((e.clientX - left) / width) * 100;"
    print "    const y = ((e.clientY - top) / height) * 100;"
    print "    setMagnifierPosition({ x, y });"
    print "    setCursorPosition({ x: e.clientX - left, y: e.clientY - top });"
    print "  };"
    skip = 1
    next
}
skip && /^};$/ && !found_closing {
    found_closing = 1
    skip = 0
    print ""
    print "  return ("
    print "    <div className=\"space-y-4\">"
    print "      {/* Main Image with Magnifier */}"
    print "      <motion.div"
    print "        className=\"relative bg-[#1E293B] rounded-2xl overflow-hidden aspect-square\""
    print "        initial={{ opacity: 0, scale: 0.9 }}"
    print "        animate={{ opacity: 1, scale: 1 }}"
    print "        transition={{ duration: 0.5 }}"
    print "      >"
    print "        <div"
    print "          className=\"relative w-full h-full cursor-crosshair\""
    print "          onMouseEnter={() => setShowMagnifier(true)}"
    print "          onMouseLeave={() => setShowMagnifier(false)}"
    print "          onMouseMove={handleMouseMove}"
    print "        >"
    print "          <WatermarkedImage"
    print "            src={processedImages[currentImage]}"
    print "            alt={\\`${productTitle} - Image ${currentImage + 1}\\`}"
    print "            className=\"w-full h-full object-contain\""
    print "          />"
    print ""
    print "          {/* Magnifier Lens */}"
    print "          {showMagnifier && ("
    print "            <div"
    print "              className=\"absolute pointer-events-none border-4 border-white rounded-full shadow-2xl\""
    print "              style={{"
    print "                width: '\''150px'\'',"
    print "                height: '\''150px'\'',"
    print "                left: \\`${cursorPosition.x - 75}px\\`,"
    print "                top: \\`${cursorPosition.y - 75}px\\`,"
    print "                backgroundImage: \\`url(${processedImages[currentImage]})\\`,"
    print "                backgroundPosition: \\`${magnifierPosition.x}% ${magnifierPosition.y}%\\`,"
    print "                backgroundSize: '\''250%'\'',"
    print "                backgroundRepeat: '\''no-repeat'\''"
    print "              }}"
    print "            />"
    print "          )}"
    print "        </div>"
    print ""
    print "        {/* Navigation Arrows */}"
    print "        {processedImages.length > 1 && ("
    print "          <>"
    print "            <button"
    print "              onClick={prevImage}"
    print "              className=\"absolute left-4 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70 text-white p-3 rounded-full transition-all duration-300 z-10\""
    print "            >"
    print "              <ChevronLeft size={24} />"
    print "            </button>"
    print "            <button"
    print "              onClick={nextImage}"
    print "              className=\"absolute right-4 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70 text-white p-3 rounded-full transition-all duration-300 z-10\""
    print "            >"
    print "              <ChevronRight size={24} />"
    print "            </button>"
    print "          </>"
    print "        )}"
    print ""
    print "        {/* Image Indicator */}"
    print "        {processedImages.length > 1 && ("
    print "          <div className=\"absolute bottom-4 left-1/2 -translate-x-1/2 flex space-x-2\">"
    print "            {processedImages.map((_, index) => ("
    print "              <div"
    print "                key={index}"
    print "                className={\\`w-2 h-2 rounded-full transition-all duration-300 ${"
    print "                  index === currentImage ? '\''bg-[#F1C27D]'\'' : '\''bg-white/50'\''"
    print "                }\\`}"
    print "              />"
    print "            ))}"
    print "          </div>"
    print "        )}"
    print "      </motion.div>"
    print ""
    print "      {/* Thumbnail Navigation */}"
    print "      {processedImages.length > 1 && ("
    print "        <div className=\"flex space-x-2 overflow-x-auto pb-2\">"
    print "          {processedImages.map((image, index) => ("
    print "            <button"
    print "              key={index}"
    print "              onClick={() => setCurrentImage(index)}"
    print "              className={\\`flex-shrink-0 w-20 h-20 rounded-lg overflow-hidden border-2 transition-all duration-300 ${"
    print "                index === currentImage"
    print "                  ? '\''border-[#F1C27D] scale-110'\''"
    print "                  : '\''border-transparent hover:border-[#94A3B8]'\''"
    print "              }\\`}"
    print "            >"
    print "              <img"
    print "                src={image}"
    print "                alt={\\`Thumbnail ${index + 1}\\`}"
    print "                className=\"w-full h-full object-cover\""
    print "              />"
    print "            </button>"
    print "          ))}"
    print "        </div>"
    print "      )}"
    print "    </div>"
    print "  );"
    print "};"
    next
}
!skip { print }
' ProductDetail.jsx > ProductDetail.jsx.tmp

mv ProductDetail.jsx.tmp ProductDetail.jsx

echo "✅ Magnifier feature added!"
